# Generated by Django 2.1.3 on 2018-12-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181203_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='repository.Comment'),
        ),
    ]
