# Generated by Django 2.1.3 on 2018-11-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181126_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=255, verbose_name='Article Summary'),
        ),
    ]
