# Generated by Django 2.1.3 on 2018-12-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20181203_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='eTicket',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'processing'), (3, 'closed')], default=1)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer', to='repository.UserInfo')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='repository.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='eTicketContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('is_reply', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.eTicket')),
            ],
        ),
    ]
