# Generated by Django 2.1.3 on 2018-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_eticket_eticketcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticketcontent',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
