# Generated by Django 2.1.3 on 2018-12-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_eticketcontent_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticket',
            name='claimer',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='eticketcontent',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='eTicket',
        ),
        migrations.DeleteModel(
            name='eTicketContent',
        ),
    ]
