# Generated by Django 2.1.3 on 2018-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_eticket_eticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticketreply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
