# Generated by Django 2.1.3 on 2018-12-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20181213_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETicket',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'processing'), (2, 'closed')], default=0)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer', to='repository.UserInfo')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='repository.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ETicketContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ETicket')),
            ],
        ),
        migrations.CreateModel(
            name='ETicketSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ETicketContent')),
            ],
        ),
    ]
