# Generated by Django 2.1.3 on 2018-12-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_eticketreply_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticketreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ETicketReply'),
        ),
    ]
