# Generated by Django 2.1.3 on 2018-12-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20181214_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticketreply',
            name='reply',
        ),
    ]
