# Generated by Django 2.1.3 on 2018-12-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission2action',
            unique_together={('p', 'a')},
        ),
    ]
